codecov:
  branch: development
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: 75%
    patch:
      default:
        enabled: yes
        target: 75%
    changes: no

  ignore: # files and folders for processing
    - build/*
    - client/*
    - server/views/*
    - server/controllers/public/*
    - spec/*
    - gulpfile*
    - gulp.config*

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
