version: "2"

services:
  shared-server:
    depends_on:
      - postgres
      - redis
    image: lmasello/music-io-shared-server
    env_file: .docker-env
    ports:
      - "8080:80"
  postgres:
    image: postgres
    env_file: .docker-env
  redis:
    image: redis:alpine
